# Generated by Django 3.2.5 on 2021-07-05 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='demo link')),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='source link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
