# Generated by Django 3.2.5 on 2021-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210705_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_iamge',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
