# Generated by Django 3.2.5 on 2021-07-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_iamge',
            new_name='featured_image',
        ),
    ]
