# Generated by Django 3.2.5 on 2021-08-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210802_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', '-title'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
